# -*- coding: utf-8 -*-
"""practice_chromaDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19blmrHeNrKl5ggrZ5YHXPJ43N1YrOAJX
"""

pip install chromadb

import chromadb

chroma_client = chromadb.Client()

collections = chroma_client.create_collection(name = "my_collection")

collections.add(
    documents = ["my name is akshath","my name is not akshath"],
    metadatas = [{"source":"my_source"},{"source":"my_source"}],
    ids = ["id1","id2"]
)

results = collections.query(
    query_texts = ["what is my name"],
    n_results = 1
)

print(results)