# -*- coding: utf-8 -*-
"""basics_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19r3cCsEyi4SQejz8ZQKFbvV295KAEJqB
"""

import numpy as np

usd=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
inr=usd*75
print(inr)

per_unit_price=np.array([20,30,15])
sold=np.array([[50,60,25],[10,13,5],[40,70,52]])

totalsales=np.dot(per_unit_price,sold)
print(totalsales)