# -*- coding: utf-8 -*-
"""Exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHAs_4EMGYlwt-W_YxRkjZ60p_roMmFD
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
train_images.shape

train_images.shape

plt.imshow(train_images[0])

plt.figure(figsize=(3,3))
for i in range(5):
    plt.imshow(train_images[i])
    plt.xlabel(class_names[train_labels[i]])
    plt.show()

train_labels[0]

train_images_scaled = train_images / 255.0
test_images_scaled = test_images / 255.0

def get_model(hidden_layers=1):
  layers = [
      keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(10, activation='softmax')
  ]
  model = keras.Sequential(layers)
  model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
  return model

model = get_model(1)
model.fit(train_images_scaled, train_labels, epochs=5)

model.predict(test_images_scaled)