# -*- coding: utf-8 -*-
"""F1score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sc91nglFSjE7pQHq2iX_KJg7OTEhLQ3r
"""

from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix , classification_report
import pandas as pd
import seaborn as sns

def print_confusion_matrix(confusion_matrix, class_names, figsize = (10,7),fontsize=14):
  df_cm = pd.DataFrame(
        confusion_matrix, index=class_names, columns=class_names,
    )
  fig = plt.figure(figsize=figsize)
  try:
      heatmap = sns.heatmap(df_cm, annot=True, fmt="d")
  except ValueError:
      raise ValueError("Confusion matrix values must be integers.")
  heatmap.yaxis.set_ticklabels(heatmap.yaxis.get_ticklabels(), rotation=0, ha='right', fontsize=fontsize)
  heatmap.xaxis.set_ticklabels(heatmap.xaxis.get_ticklabels(), rotation=45, ha='right', fontsize=fontsize)
  plt.ylabel('Truth')
  plt.xlabel('Prediction')

truth =      ["Dog","Not a dog","Dog","Dog",      "Dog", "Not a dog", "Not a dog", "Dog",       "Dog", "Not a dog"]
prediction = ["Dog","Dog",      "Dog","Not a dog","Dog", "Not a dog", "Dog",       "Not a dog", "Dog", "Dog"]

cm = confusion_matrix(truth,prediction)
print_confusion_matrix(cm,["Dog","Not a dog"])

print(classification_report(truth, prediction))