# -*- coding: utf-8 -*-
"""practice_loss/costfunc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1umsRXHAF0HI4wFxM3zSmUcgHkIX_y3Hu
"""

import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

np.mean(np.square(y_true-y_predicted))