# -*- coding: utf-8 -*-
"""AIDS_linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17U19_fCuf_sZ8B0AdvKR4TCp4D9TCFhw
"""

#from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

my_url="https://github.com/codebasics/py/raw/refs/heads/master/ML/1_linear_reg/Exercise/canada_per_capita_income.csv"
df=pd.read_csv(my_url)
df.head()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income(US$)')
plt.scatter(df.year,df['per capita income (US$)'], color='red', marker='+')

reg=linear_model.LinearRegression()
reg.fit(df[['year']],df['per capita income (US$)'])

reg.predict([[1990]])

reg.coef_

reg.intercept_

d=pd.read_csv('linearreg_predict.csv')
d.head()

p=reg.predict(d)

828.46507522*1990-1632210.7578554575

d['per capita income (US$)']=p
d

d.to_csv("prediction.csv",index=False)
d.head()

plt.xlabel('year')
plt.ylabel('per capita income(US$)')
plt.scatter(df.year,df['per capita income (US$)'], color='red', marker='+')
plt.plot(df.year,reg.predict(df[['year']]), color='orange')

import pickle
with open('model_pickle','wb') as f:
  pickle.dump(reg,f)

with open('model_pickle','rb') as f:
  reg=pickle.load(f)

reg.coef_