# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZgj2vwQtVZNzBG1ei_7HZy6wC8lBbHq
"""

import pandas as pd
df=pd.read_csv('titanic.csv')
df

final=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
final

x=pd.get_dummies(final.Sex,dtype='int')
x

z=pd.concat([final,x],axis='columns')
z

X=z.drop(['Sex','male','Survived'],axis='columns')
X

X['Age'].isnull().sum()

X['Age']=X['Age'].fillna(X['Age'].median())

y=final.Survived
y

from sklearn import tree

model=tree.DecisionTreeClassifier()
model.fit(X,y)

model.score(X,y)