# -*- coding: utf-8 -*-
"""linreg_multi_variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIhnBUHDhBtObLPL5Ckg8wDpV5bWHA2o
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df=pd.read_csv('hiring.csv')
df

!pip install word2number
from word2number import w2n

df.experience=df.experience.fillna('zero')
df

a=int(df['test_score(out of 10)'].mean())
print(a)

df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(a)
df

df.experience=df.experience.apply(w2n.word_to_num)
df

reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

reg.predict([[2,9,6]])

import joblib

joblib.dump(reg,'model_joblib')

model_object=joblib.load('model_joblib')

model_object.coef_