# -*- coding: utf-8 -*-
"""Logistic_reg_Binary_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnKQkOoAh5QPvznuXidFkAtmWrq8D3Kv
"""

import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split

df=pd.read_csv('HR_comma_sep.csv')
df.head()

df.info()

df.describe()

pd.crosstab(df.salary,df.left).plot(kind='bar')

pd.crosstab(df.Department,df.left).plot(kind='bar')

final=df.drop(['last_evaluation','number_project','time_spend_company','Work_accident','Department'],axis='columns')
final

before_left=pd.get_dummies(final,dtype='int')
before_left.head()

X=before_left.drop(['salary_low','left'],axis='columns')

y=before_left.left
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

X_train

y_test

from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()

reg.fit(X_train,y_train)

reg.predict(X_test)

reg.score(X_test,y_test)