# -*- coding: utf-8 -*-
"""Naive_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dDTFJkM1s_PAkY9V_gcJ2wMAoclHlgbi
"""

import pandas as pd
from sklearn import datasets
wine=datasets.load_wine()

dir(wine)

wine.feature_names

df=pd.DataFrame(wine.data,columns=wine.feature_names)
df

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,train_size=0.2,random_state=100)

from sklearn.naive_bayes import GaussianNB,MultinomialNB
model=GaussianNB()
model.fit(X_train,y_train)

model.score(X_test,y_test)

mnb=MultinomialNB()
mnb.fit(X_train,y_train)

mnb.score(X_test,y_test)