# -*- coding: utf-8 -*-
"""One_hot_encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ET2BrpEqdsSVw2AwIU5lS4WsnS0my6de
"""

import pandas as pd
from sklearn import linear_model

df=pd.read_csv('carprices.csv')
df

d=pd.get_dummies(df,dtype=int)

X=d.drop(['Sell Price($)','Car Model_Mercedez Benz C class'],axis='columns')
X

y=df['Sell Price($)']

reg=linear_model.LinearRegression()
reg.fit(X,y)